### ISSUE TITLE
Link Statamic customers from Shopify

### ISSUE THREAD

**Issue by ryanhissey** [statamic-rad-pack/shopify#194]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] All relevant scopes have been applied within the shopify admin for the app

# Expected Behavior

I was expecting the user to be created and synced to shopify.

# Current Behavior

The user is created within statamic, but never syncs to Shopify. An exception is also thrown here too. 

# Failure Information

Here is an example of when I try to make a user from the statamic CLI

<img width="986" alt="Screenshot 2023-11-08 at 16 47 20" src="https://github.com/statamic-rad-pack/shopify/assets/9078889/ade6aa88-d886-4942-be03-2e954eab4338">

Error in Log:
`[2023-11-08 16:47:03] local.ERROR: Could not create user in Shopify {"exception":"[object] (Exception(code: 0): Could not create user in Shopify at /vendor/statamic-rad-pack/shopify/src/Jobs/CreateOrUpdateShopifyUser.php:61)
[stacktrace]`

A snippet of a dd illustrating the response in the rest client:

<img width="304" alt="Screenshot 2023-11-09 at 23 18 13" src="https://github.com/statamic-rad-pack/shopify/assets/9078889/8012fceb-950c-422f-a796-218c4b3aa633">

## Steps to Reproduce

`php please make:user`

or

Make a new user within the admin

## Context

* Plugin Version:  v3.0.2
* Statamic Version: v4.32.0
* PHP Version: 8.2.11
* Shopify-api: v5.2.0

**Comment by ryanmitchell** [comment]
Did you add the correct permissions in your Shopify app:
https://statamic-shopify-docs.vercel.app/CMS/customers#link-statamic-customers-from-shopify

**Comment by ryanhissey** [comment]
Hey @ryanmitchell,

Thanks for the reply. I have added the correct permissions to the app. 

<img width="589" alt="Screenshot 2023-11-10 at 07 49 15" src="https://github.com/statamic-rad-pack/shopify/assets/9078889/37b18b98-af94-483a-ac8a-36a7d88ac2ee">

**Comment by ryanmitchell** [comment]
Yeah I think i see why - do you want to give the [changes here](https://github.com/statamic-rad-pack/shopify/pull/195) a go and let me know if that solves it for you?

**Comment by ryanhissey** [comment]
@ryanmitchell - Unfortunately this does not fix the issue, That return should definitely be there though. 

It looks like the error is still stemming from the 401 unauthorised, from the response in the rest client.

**Comment by ryanmitchell** [comment]
I've pushed some updates - verified it against a couple of our accounts. It's definitely working now.
Attached a screenshot of the permissions we've enabled.

![CleanShot 2023-11-10 at 16 54 02@2x](https://github.com/statamic-rad-pack/shopify/assets/51899/ace7838f-a5b8-43bf-8037-faf0044a4e62)

**Comment by ryanhissey** [comment]
Hmm how strange. 

I've tested the code from your PR on my project, Still have the same issue. I've also triple-checked that all permissions are enabled. 

Still the 401

**Comment by ryanmitchell** [comment]
Strange indeed, looks like some of your credentials arent right.
I'm happy to work with you directly on it if you want to DM me on discord.
